#!/usr/bin/env bash

if [[ $OSTYPE == darwin* ]]; then # do the needful things on MacOS
  # taken from http://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/
  alias showhidden="defaults write com.apple.finder AppleShowAllFiles YES" # display hidden files
  alias hidehidden="defaults write com.apple.finder AppleShowAllFiles NO" # hide hidden files
  # unsure of source for this. Probably googlephoo
  alias flushdns="sudo killall -HUP mDNSResponder;sudo killall mDNSResponderHelper;sudo dscacheutil -flushcache"

  # Finder Customisations
  defaults write com.apple.finder_FXShowPosixPathInTitle -bool true
  killall Finder

  # adding brew items to $PATH if brew is installed.
  if [[ -e `which brew` ]]; then
    export PATH=/usr/local/bin:/usr/local/sbin:$PATH
  fi

elif [[ $OSTYPE == "linux-gnu" ]]; then # do the needful things on Linux
  :
fi

# do the needful things on any *nix
# Enable AWS CLI completion if AWS CLI is installed
if [[ -e `which aws_completer` ]]; then
  complete -C "which aws_completer" aws
fi

# Configure our AWS profile switching shortcut if we have it installed
if [[ -f ~/._awsAliases ]]; then
  # shellcheck source=_awsAliases
  . ~/._awsAliases
  alias awsall="_awsListAll"
  alias awsp="_awsSwitchProfile"
  alias awswho="aws configure list"
fi

# alias for us to pull and refresh our dotfiles.
if [[ -d ~/andrews-configs ]]; then
  # target directory already exists
  # just cd to it and pull the files.
  alias refreshdotfiles="cd ~/andrews-configs || exit && git pull origin master && ~/andrews-configs/dotfiles/makesymlinks.sh"
else
  # target directory doesnt exist. We need to install it for the first time.
  cd ~ || exit
  git clone https://github.com/ausfestivus/andrews-configs.git
  ~/andrews-configs/dotfiles/makesymlinks.sh
  # shellcheck source=/dev/null
  source ~/.bash_profile
fi


# Personal - home shortcuts
alias homegw="ssh -i ~/.ssh/id_rsa admin@homegw.mtcolah.bestfamily.id.au -p 2222"
alias homegw-root="ssh -i ~/.ssh/id_rsa root@homegw.mtcolah.bestfamily.id.au -p 2222"
alias nasquith="ssh -i ~/.ssh/id_rsa festivus@nasquith.mtcolah.bestfamily.id.au -p 2223"
alias raspberrypi="ssh -i ~/.ssh/id_rsa pi@raspberrypi.mtcolah.bestfamily.id.au -p 2224"
# Personal - AWS shortcuts
#
# Personal - Azure shortcuts
alias azjump="ssh ubuntu@jump00.cloud00.bestfamily.id.au"
#
# Personal - Alibaba shortcuts
#alias alijump="ssh -i ~/.ssh/alibabacloud abest@jump.cloud01.bestfamily.id.au"
#
# Diaxion - Azure shortcuts
alias azjira="ssh -i ~/.ssh/azure-ubuntu-default ubuntu@diapapp04.australiasoutheast.cloudapp.azure.com"
alias azconfluence="ssh -i ~/.ssh/azure-ubuntu-default ubuntu@diapapp05.australiasoutheast.cloudapp.azure.com"
alias azterraform="ssh -i ~/.ssh/azure-ubuntu-default ubuntu@terraform.diaxion.com"
#
# Diaxion - AWS shortcuts # none Currently
#
# Diaxion - GWF shortcuts
# alias gnrlabproxy="ssh -i ~/.ssh/id_rsa ubuntu@gnrlabproxy.gwf.com.au"
# alias gnrlabubuntu="ssh -i ~/.ssh/id_rsa ubuntu@10.1.154.40"
# alias ic1smokeping="ssh -i ~/.ssh/id_rsa gwf@smokeping.gwf.com.au"
