#!/usr/bin/env bash

if [ $OSTYPE == "darwin16" ]; then # do the needful things on MacOS
  # taken from http://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/
  alias showhidden="defaults write com.apple.finder AppleShowAllFiles YES" # display hidden files
  alias hidehidden="defaults write com.apple.finder AppleShowAllFiles NO" # hide hidden files

  # Finder Customisations
  defaults write com.apple.finder_FXShowPosixPathInTitle -bool true
  killall Finder

  # adding brew items to $PATH if brew is installed.
  if [[ -e `which brew` ]]; then
    export PATH=/usr/local/bin:/usr/local/sbin:$PATH
  fi

  elif [ $OSTYPE == "linux-gnu" ]; then # do the needful things on Linux
  :
fi

# do the needful things on any *nix
# Enable AWS CLI completion if AWS CLI is installed
if [[ -e `which aws_completer` ]]; then
  complete -C "which aws_completer" aws
fi

# Configure our AWS profile switching shortcut if we have it installed
if [[ -f ~/._awsAliases ]]; then
  # shellcheck source=_awsAliases
  . ~/._awsAliases
  alias awsall="_awsListAll"
  alias awsp="_awsSwitchProfile"
  alias awswho="aws configure list"
fi

# Personal - home shortcuts
# nasquith
alias nasquith="ssh -i ~/.ssh/id_rsa festivus@nasquith.mtcolah.bestfamily.id.au"
alias homegw="ssh -i ~/.ssh/id_rsa admin@homegw.mtcolah.bestfamily.id.au"
# Personal - AWS shortcuts
#
# Personal - Alibaba shortcuts
alias alijump="ssh -i ~/.ssh/alibabacloud abest@jump.cloud01.bestfamily.id.au"
#
# Diaxion - Azure shortcuts
alias azjira="ssh -i ~/.ssh/azure-ubuntu-default ubuntu@diapapp01.australiasoutheast.cloudapp.azure.com"
alias azconfluence="ssh -i ~/.ssh/azure-ubuntu-default ubuntu@diapapp02.australiasoutheast.cloudapp.azure.com"
# Diaxion - AWS shortcuts
# none Currently
# Diaxion - GWF shortcuts
alias gnrlabproxy="ssh -i ~/.ssh/id_rsa ubuntu@gnrlabproxy.gwf.com.au"
alias gnrlabubuntu="ssh -i ~/.ssh/id_rsa ubuntu@10.1.154.40"
alias ic2smokeping="ssh -i ~/.ssh/id_rsa gwf@10.0.235.110"
