#!/usr/bin/env bash
# Enable AWS CLI completion if AWS CLI is installed
if [ `which aws_completer` ]; then
  complete -C `which aws_completer` aws
fi

# Configure our AWS profile switching shortcut if we have it installed
if [ -f ~/._awsAliases ]; then
  . ~/._awsAliases
  alias awsall="_awsListAll"
  alias awsp="_awsSwitchProfile"
  alias awswho="aws configure list"
fi

if [ $OSTYPE == "darwin16" ]; then
  # taken from http://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/
  # display hidden files
  alias showhidden="defaults write com.apple.finder AppleShowAllFiles YES"
  # hide hidden files
  alias hidehidden="defaults write com.apple.finder AppleShowAllFiles NO"
elif [ $OSTYPE == "linux-gnu" ]; then
  :
else
  # Personal - home shortcuts
  # nasquith
  alias nasquith="ssh -i ~/.ssh/id_rsa festivus@192.168.1.1"
  # Personal - AWS shortcuts

  # Diaxion - Azure shortcuts
  alias azjira="ssh -i ~/Documents/_My\ Projects/201701-Diaxion\ Azure\ Migration/azure-ubuntu-default ubuntu@diapapp01.australiasoutheast.cloudapp.azure.com"
  alias azconfluence="ssh -i ~/Documents/_My\ Projects/201701-Diaxion\ Azure\ Migration/azure-ubuntu-default ubuntu@diapapp02.australiasoutheast.cloudapp.azure.com"
  # Diaxion - AWS shortcuts
  # none Currently
fi
